# Fallback workspace assignment before workspace-monitor-profile updates it.

workspace = 1, monitor:eDP-2, default:true, persistent:true
workspace = 2, monitor:eDP-2, persistent:true
workspace = 3, monitor:eDP-2, persistent:true
workspace = 4, monitor:eDP-2, persistent:true
workspace = 5, monitor:eDP-2, persistent:true
workspace = 6, monitor:eDP-2, persistent:true
workspace = 7, monitor:eDP-2, persistent:true
workspace = 8, monitor:eDP-2, persistent:true
workspace = 9, monitor:eDP-2, persistent:true
